// Check the design's state/brief behavior without claiming Blender or browser integration.
const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
const input = process.argv[2];
const output = process.argv[3];
if (!input || !output) throw Error('Usage: node check_author_wizard_design.cjs fragment.html report.json');
const html = fs.readFileSync(input, 'utf8');
const scripts = [...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(x => x[1]);
scripts.forEach((s, i) => new vm.Script(s, {filename:'wizard-script-'+i+'.js'}));
const ctx = vm.createContext({});
vm.runInContext(scripts[0], ctx);
const M = ctx.AWDesign;
const passed=[];
function check(name, test){test();passed.push(name);}
const makeReady=()=>{const s=M.initial();s.helper='exclude';s.confirmed=true;return s;};
check('prototype scripts compile',()=>assert.equal(scripts.length,2));
check('unknown helper blocks completion',()=>assert.equal(M.ready(M.initial()),false));
check('scope requires explicit confirmation',()=>{const s=M.initial();s.helper='exclude';assert.equal(M.ready(s),false);});
check('confirmed unmeasured description can complete',()=>assert.equal(M.ready(makeReady()),true));
check('Workspace removed from whole scope and nested arm assignment',()=>{const s=makeReady();assert(!M.included(s).includes('workspace'));assert(!M.candidates(s,'r','branch').includes('workspace'));});
check('explicit Keep remains supported',()=>{const s=makeReady();s.helper='keep';assert(M.included(s).includes('workspace'));assert(M.ready(s));});
check('base Selected Only does not include tool descendants',()=>{const s=makeReady();assert.equal(M.candidates(s,'b','self').join(','),'b');assert(M.candidates(s,'b','branch').includes('bgb'));});
check('Empty self selection does not become physical geometry',()=>assert.equal(M.candidates(makeReady(),'r','self').length,0));
check('overlapping mesh assignments require correction',()=>{const s=makeReady();assert.equal(M.assign(s,'base','b','self'),null);assert.equal(typeof M.assign(s,'handler','b','branch'),'string');});
check('excluded root unavailable to assignment',()=>{const s=makeReady();s.roots=['b'];assert.equal(M.candidates(s,'r','branch').length,0);});
check('arm count creates matching active cards and text',()=>{const s=makeReady();s.arms='2';s.armData.arm2={kind:'SCARA',axes:'4'};assert.equal(M.parts(s).filter(p=>p.id.startsWith('arm')).length,2);assert(M.text(s).includes('arm2=SCARA,4 axes'));s.arms='1';assert(!M.text(s).includes('arm2='));assert.equal(s.armData.arm2.axes,'4');});
check('unknown arm count never inferred from source mesh count',()=>{const s=makeReady();s.arms='Unknown';assert(M.text(s).includes('arms=Unknown'));assert(!M.text(s).includes('arm1='));});
check('disabled handler removes its motion relationship',()=>{const s=makeReady();s.handler=false;assert(!M.text(s).includes('vertical_relation='));});
check('independent vertical motion preserved without invented columns',()=>{const t=M.text(makeReady());assert(t.includes('vertical_relation=Independent'));assert(t.includes('mounting=unknown'));assert(!t.includes('columns=2'));});
check('actual dimensions remain unmeasured',()=>assert(M.text(makeReady()).includes('overall=unmeasured')));
check('example dimensions are explicitly illustrative',()=>{const s=makeReady();s.includeDemo=true;s.demoRevision=s.revision;const t=M.text(s);assert(t.includes('ILLUSTRATIVE_ONLY_size_m='));assert(t.includes('overall=unmeasured'));});
check('scope revision invalidates confirmation and example values',()=>{const s=makeReady();s.includeDemo=true;s.demoRevision=s.revision;M.changeScope(s);assert(!s.confirmed);s.confirmed=true;assert(!M.ready(s));s.includeDemo=false;assert(M.ready(s));});
check('1000 passes, 1001 blocks without truncation',()=>{const s=makeReady();s.features='x';const n=M.text(s).length-1;s.features='x'.repeat(1000-n);assert.equal(M.text(s).length,1000);assert(M.ready(s));s.features+='x';assert.equal(M.text(s).length,1001);assert(!M.ready(s));assert.equal(s.features.length,1001-n);});
check('Unicode emoji counted as two UTF-16 units',()=>{const s=makeReady();s.features='x';const n=M.text(s).length-1;s.features='가😀';assert.equal(M.text(s).length-n,3);});
check('source names optional and not sent by default',()=>{const s=makeReady();assert(!M.text(s).includes('RobotRoot'));s.includeHierarchy=true;assert(M.text(s).includes('RobotRoot'));});
check('free text escaped rather than becoming new fields',()=>{const s=makeReady();s.purpose='test;arms=9\n"x"';assert(M.text(s).includes('purpose='+JSON.stringify(s.purpose)));});
check('no external resources or network code in prototype',()=>{assert(!/<script[^>]+src=|<link[^>]+href=|\bfetch\s*\(|XMLHttpRequest|WebSocket/.test(html));});
check('stable unique source ids and valid parents',()=>{assert.equal(new Set(M.nodes.map(n=>n.id)).size,M.nodes.length);M.nodes.forEach(n=>assert(!n.parent||M.node(n.parent)));});
const sample=M.text(makeReady());
fs.mkdirSync(path.dirname(output),{recursive:true});
fs.writeFileSync(output,JSON.stringify({status:'passed',checks:passed.length,passed,sample_characters:sample.length,example_source_objects:M.nodes.length,example_physical_meshes:M.included(makeReady()).length,scope:'Pure model and JavaScript syntax only. No actual Blender integration, geometry measurement, browser layout or inline-render inspection.',sample},null,2)+'\n');
console.log(JSON.stringify({checks:passed.length,sample_characters:sample.length,report:output}));
